---
- hosts: all
  become: true
  gather_facts: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Execute tasks
      include_tasks: "{{ item }}"
      loop:
        - ec2-launch-docker.yaml
