#---
#- name: Create a micro instance in AWS EC2
#  hosts: localhost
#  gather_facts: false
#  vars:
#    keypair: sshtest
#    instance_type: t2.micro
#    security_group: SinensiaEC2
#    subnet_id: subnet-0bcb76bfbc6174487
#    image: ami-0d71ea30463e0ff8d
#    region: eu-west-1
#  tasks:
#    - name: Launch instance
#      ec2:
#        key_name: "{{ keypair }}"
#        group: "{{ security_group }}"
#        instance_type: "{{ instance_type }}"
#        image: "{{ image }}"
#        wait: true
#        region: "{{ region }}"
#        vpc_subnet_id: "{{ subnet_id }}"
#        assign_public_ip: yes
#        instance_tags:
#          Name: ansibleInstance
#      register: ec2
#
#    - name: Add new instance to host group
#      add_host:
#        hostname: "{{ item.public_ip }}"
#        groupname: launched
#      loop: "{{ ec2.instances }}"
#
#    - name: Wait for SSH to come up
#      delegate_to: "{{ item.public_dns_name }}"
#      wait_for_connection:
#        delay: 10
#        sleep: 5
#        timeout: 300
#      vars:
#       ansible_user: ec2-user
#     loop: "{{ ec2.instances }}"

- name: Configure instances
  hosts: launched
  become: true
  gather_facts: true
  vars:
    ansible_user: ec2-user
  tasks:
    - name: Install docker
      shell: amazon-linux-extras install -y docker

    - name: User add docker group
      user:
        name: ec2-user
        group: docker

    - name: Start docker
      service:
        name: docker
        enabled: true
        state: started

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose

    - name: Symlink
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
        owner: ec2-user
        mode: '0755'

    - name: Install hello-springrest
      copy:
        src: /home/sinensia/Desktop/vue-2048/docker-compose.yml
        dest: /home/ec2-user/Docker/

    - name: Pull DockersHub
      become: true
      shell: docker-compose -f /home/ec2-user/Docker/docker-compose.yml pull

    - name: Run `docker-compose up`
      become: true
      shell: docker-compose -f /home/ec2-user/Docker/docker-compose.yml up -d --no-build

